### ISSUE TITLE
Project Proposal Feedback

### ISSUE THREAD

**Issue by natec425** [BaseCampCoding/fundamentals-of-programming-pt-1-unit-project-evan-and-lance#1]
Hey @Lance-Easley and @EvanSandersd,

Your project proposal looks good to me. I think your project sounds pretty ambitious. I would be careful today and tomorrow to make sure that the project is taking a more concrete shape instead of opening up more.

**Comment by Lance-Easley** [comment]
Got it. We'll make sure to have a solid plan to follow and stay on track.
